engine:
  download:
    end_year: 2025
    max_per_year: 100
    start_year: 2000
    ignored_reports: ['TAIC_m_2022_202', 'TAIC_m_2022_203']
    modes: ['a', 'r','m']
    agencies: ['ATSB', 'TSB', 'TAIC']
  output:
    folder_name: "output"
    container_name: "engineoutput"
    pdf_container_name: "prod-reportpdfs"
  data:
    data_remote_folder_location: "https://raw.githubusercontent.com/1jamesthompson1/TAIC-engine/main/data/"
    data_local_folder_location: "data"
    event_types_file_name: "event_types.csv"
  extraction:
    ai_extraction_config:
      ATSB:
        safety_issues: false
        recommendations: true
        metadata: true
      TSB:
        safety_issues: true
        recommendations: false
        metadata: true
      TAIC:
        safety_issues: true
        recommendations: false
        metadata: true
  vector:
    table_name: "all_document_types"  # LanceDB table name
    model:
      name: "text-embedding-3-large"
      context_limit: 8191  # Approx token context limit for truncation logic