import hashlib
import os
from unittest.mock import patch

import numpy as np
import pytest

import engine.analyze.Embedding as Embedding


def test_basic_embedding(tmpdir):
    vector_db = None
    generated_embeddings = []

    def mock_generate_embeddings(self, texts, *args, **kwargs):
        # normalize input
        if isinstance(texts, np.ndarray):
            if texts.dtype != object:
                raise ValueError(
                    "AzureAIEmbeddingFunction only supports input of strings for numpy arrays."
                )
            texts = texts.tolist()

        result = []
        dim = self.ndims()
        for text in texts:
            seed = int(hashlib.sha256(str(text).encode("utf-8")).hexdigest(), 16) % (
                2**32
            )
            rng = np.random.default_rng(seed)
            emb = rng.random(dim).astype(np.float32).tolist()
            result.append(emb)
            generated_embeddings.append(emb)
        return result

    try:
        extracted_df_path = os.path.join(
            pytest.output_config["folder_name"],
            pytest.output_config["extracted_reports_df_file_name"],
        )

        # Initialize VectorDB instance
        test_db_uri = os.getenv("TEST_VECTORDB_URI")
        assert test_db_uri, "TEST_VECTORDB_URI environment variable must be set."

        # Create a temporary path for local embedded IDs
        temp_path = tmpdir.join("local_embedded_ids")

        # Patch embedding generation to a fast deterministic mock that returns correct-sized vectors
        with patch.object(
            Embedding.AzureAITextEmbeddingFunction,
            "generate_embeddings",
            new=mock_generate_embeddings,
        ):
            vector_db = Embedding.VectorDB(
                local_embedded_ids_path=temp_path,
                db_uri=test_db_uri,
                model_name=pytest.vector_config["model"]["name"],
                table_name=pytest.vector_config["table_name"],
                context_limit=pytest.vector_config["model"]["context_limit"],
            )

            vector_db.process_extracted_reports(
                extracted_df_path,
                [
                    (
                        "safety_issues",
                        "safety_issue",
                    ),
                    (
                        "recommendations",
                        "recommendation",
                    ),
                    (
                        "sections",
                        "section",
                    ),
                    (
                        "summary",
                        "summary",
                    ),
                ],
            )

            # Verify table exists
            assert vector_db.table_name in vector_db.db.table_names()

            # Verify that the table has rows
            assert vector_db.table.count_rows() > 0, "The table should have rows."

            # Ensure embeddings were generated and have the expected dimensionality
            azure_embeddings = (
                Embedding.EmbeddingFunctionRegistry.get_instance()
                .get("azure-ai-text")
                .create(name=pytest.vector_config["model"]["name"])
            )
            expected_dim = azure_embeddings.ndims()
            assert generated_embeddings, "No embeddings were generated by the mock."
            assert all(
                len(e) == expected_dim for e in generated_embeddings
            ), f"Expected embeddings of length {expected_dim}, got {[len(e) for e in generated_embeddings][:5]}"

    finally:
        if vector_db:
            # Drop all tables
            vector_db.db.drop_all_tables()

            # Ensure tables are dropped
            assert not vector_db.db.table_names()
