"""Tests for Embedding module."""

import hashlib
from datetime import datetime
from unittest.mock import patch

import numpy as np
import pandas as pd
import pytest

from engine import Embedding, SavedDataFrames


def test_basic_embedding(tmp_path: object) -> None:
    """Test the embedding pipeline using the saved dataframe flow."""
    generated_embeddings: list[list[float]] = []

    def mock_generate_embeddings(
        self: object, texts: object, *args: object, **kwargs: object
    ) -> list[list[float]]:
        if isinstance(texts, np.ndarray):
            if texts.dtype != object:
                msg = "AzureAIEmbeddingFunction only supports input of strings for numpy arrays."
                raise ValueError(msg)
            texts = texts.tolist()

        result = []
        dim = self.ndims()
        for text in texts:
            seed = int(hashlib.sha256(str(text).encode("utf-8")).hexdigest(), 16) % (
                2**32
            )
            rng = np.random.default_rng(seed)
            emb = rng.random(dim).astype(np.float32).tolist()
            result.append(emb)
            generated_embeddings.append(emb)
        return result

    complete_data_dc = SavedDataFrames.DataForVectorDB(tmp_path)
    already_embedded_ids_dc = SavedDataFrames.VectorDBDocumentIDs(tmp_path)

    complete_data = pd.DataFrame(
        [
            {
                "report_id": "TAIC_m_2024_001",
                "document_id": "TAIC_m_2024_001_sum_0",
                "document": "A short report text about an incident.",
                "document_type": "summary",
                "url": "https://example.com/report/1",
                "location": "Auckland",
                "occurrence_date": datetime(2024, 1, 15),
                "occurrence_type": "Accident",
                "fatalities": 0,
                "injuries": 1,
                "damage": "Minor damage",
                "who_may_benefit": "Operators",
                "agency_id": "TAIC",
                "mode": "m",
                "year": 2024,
                "agency": "TAIC",
            },
            {
                "report_id": "TAIC_a_2024_002",
                "document_id": "TAIC_a_2024_002_sum_0",
                "document": "Another short report text about a second incident.",
                "document_type": "summary",
                "url": "https://example.com/report/2",
                "location": "Wellington",
                "occurrence_date": datetime(2024, 2, 20),
                "occurrence_type": "Incident",
                "fatalities": 0,
                "injuries": 0,
                "damage": "No damage",
                "who_may_benefit": "Investigators",
                "agency_id": "TAIC",
                "mode": "a",
                "year": 2024,
                "agency": "TAIC",
            },
        ],
        columns=complete_data_dc._effective_columns,
    )
    complete_data_dc.save(complete_data)

    test_db_uri = str(tmp_path / "vectordb")
    vector_db = None

    try:
        with patch.object(
            Embedding.AzureAITextEmbeddingFunction,
            "generate_embeddings",
            new=mock_generate_embeddings,
        ):
            vector_db = Embedding.VectorDB(
                db_uri=test_db_uri,
                model_name=pytest.vector_config["model"]["name"],
                context_limit=pytest.vector_config["model"]["context_limit"],
                table_name="all_document_types_test",
            )

            vector_db.process_extracted_reports(
                complete_data_dc,
                already_embedded_ids_dc,
            )

        assert vector_db.table_name in vector_db.db.table_names()
        assert vector_db.table.count_rows() == len(complete_data)

        azure_embeddings = (
            Embedding.EmbeddingFunctionRegistry.get_instance()
            .get("azure-ai-text")
            .create(name=pytest.vector_config["model"]["name"])
        )
        expected_dim = azure_embeddings.ndims()
        assert generated_embeddings, "No embeddings were generated by the mock."
        assert all(
            len(e) == expected_dim for e in generated_embeddings
        ), f"Expected embeddings of length {expected_dim}, got {[len(e) for e in generated_embeddings][:5]}"

        saved_ids = already_embedded_ids_dc.read()
        assert len(saved_ids) == len(complete_data)
        assert set(saved_ids["document_id"]) == set(complete_data["document_id"])

    finally:
        if vector_db is not None:
            vector_db.db.drop_all_tables()
